/** Replies generated by xterm's parser, not keystrokes or pasted user text. */
export function isTerminalReply(data: string): boolean {
  return /^\x1b\[[\d;?>]*[Rcn]$/.test(data) || /^\x1b\](?:4|10|11|12);[^\x1b]*(?:\x07|\x1b\\)$/.test(data)
}
