/**
 * Replies generated by xterm's parser, not keystrokes or pasted user text.
 *
 * One headless parser in the main process answers every terminal query, so a
 * visible renderer must stay silent — otherwise the agent receives two answers
 * to one question and the stray one lands in its stdin. Codex and other inline
 * TUIs ask for the synchronized-output mode and the window size to place their
 * frame, so a duplicate reply there shows up as a redraw jumping between rows.
 *
 * Every shape xterm can emit is listed here:
 *   ESC [ <n> ; <n> R       cursor position (and the ESC [ ? form)
 *   ESC [ <n> n             device status
 *   ESC [ ? <n> c           device attributes
 *   ESC [ ? <n> ; <n> $y    mode support (DECRPM), including 2026
 *   ESC [ <n> ; <n> ; <n> t window, cell and text-area size reports
 *   OSC 4/10/11/12 ...      colour queries
 */
export function isTerminalReply(data: string): boolean {
  return /^\x1b\[[\d;?>]*[Rcn]$/.test(data)
    || /^\x1b\[\??[\d;]*\$y$/.test(data)
    || /^\x1b\[[\d;]*t$/.test(data)
    || /^\x1b\](?:4|10|11|12);[^\x1b]*(?:\x07|\x1b\\)$/.test(data)
}
